### ISSUE TITLE
Twitter Bootstrap compile errors

### ISSUE THREAD

**Issue by thgutmann** [bdkjones/CodeKit-1-Old#641] opened 2013-07-12 09:41 UTC
Hi
Since the last update to version 8317, codekit does complain about a parse error in mixins.less of twitter bootstrap. The same code does compile fine in version 8300.

Here's the log:
ParseError: Unrecognised input in /Users/myuser/Sites/ttw/app/webroot/bootstrap/less/mixins.less on line 561, column 7:
560     .spanX (@index) when (@index > 0) {
561       (~".span@{index}") { .span(@index); }
562       .spanX(@index - 1);

I also copied the whole bootstrap folders from another machine with codekit 8300 installed, but it keeps complaining.

**Comment by nicoandrade** [comment] 2013-07-12 14:29
Same thing for me. Looks like a problem in the Less compiler in the latest version.

**Comment by bdkjones** [comment] 2013-07-12 18:05
Please update to the latest version of Twitter Bootstrap and close the issue. This is not a bug. Less 1.4 has syntax changes that break older code. Cheers!

**Closed as completed** 2013-07-14 23:22 UTC
