### ISSUE TITLE
to Sort or not to Sort (codekit config file)

### ISSUE THREAD

**Issue by pdesterlich** [bdkjones/CodeKit-1-Old#489] opened 2013-01-10 21:18 UTC
a (not so) short story to explain a bug in a way every developer can understand it

i don't want to offend anyone, just being a little ironic (it still isn't copyright of Incident57, isn't it?) - also, i apologize if my english is far from perfect: it's not my primary language
## 

Once upon a time, in an internet far far away, there was a poor developer, commissioned to build the new website for www.superawesomecompany.org
The poor developer fired up his editor and, with great efforts, ended up with 3 files: index.html, style.less & site.js
Then the poor developer asked Mighty Codekit, ruler in the reign of developers, to take care of his project: "Mighty CodeKit, Emperor of Code, i humbly beg you to watch over my project, cause i will hardly finish it withous your help". "That i will do, my poor developer, for that i am a good ruler, and i will place one of my file with yours" answered Mighty CodeKit.
And so Mighty CodeKit watched poor developer's project, creating a small file (codekit-config.json) where he would write down his thoughts about the project.

```
codekit-config.json
{
    files: {
        index.html : { ... },
        style.less : { ... },
        site.js : { ... },
    }
}
```

Then poor developer, who was poor but wise, asked his old friend Sir BitBucket (of the Git family) to store his project, cause even a poor developer knows the benefits of being in the git family; he gave all his files to Sir BitBucket, then, tired from the hard work he made, went to sleep.
When he woke up, Sir BitBucket told him about a strange thing happened while he was sleeping: "One of your file suddenly changed", and he showed the poor developer

```
codekit-config.json
{
    files: {
        style.less : { ... },
        index.html : { ... },
        site.js : { ... },
    }
}
```

"How can that be?" asked the poor developer "i sleeped all night, having nightmares of customer angrily following me".
"That i don't know" said Sir Bitbucket, and the two started thinking who could have possibly made such a change. And while they where checking, suddenly the file changed again

```
codekit-config.json
{
    files: {
        site.js : { ... },
        index.html : { ... },
        style.less : { ... },
    }
}
```

"That i can't understand" said Sir BitBucket, perplexed.
"Wait, could that be caused by Mighty CodeKit taking care of my project?" asked the poor developer.
Again, Sir BitBucket said "That i don't know, but why don't you politely ask him?"
And so did the poor developer, asking to the ruler "Oh Mighty CodeKit, Emperor of Code, i humbly ask you: have you changed your file in my project?"
"That i did, for that i am a good ruler" answered Mighty CodeKit.
"But why, if i may dare to ask?" said poor developer.
"Cause i am so fast in watching your project that even my files can't stand my speed. So it is, and you can't do nothing about that, so do not complain, and keep on adoring me, you humble citizen of the empire".
And so that goes, and the file continuosly changes, every time Mighty CodeKit watched poor developer's project.

Then, one day, the poor developer went on a journey to spend some days with his friends. While there, he received a message from the Super Awesome Company, asking him to make some changes in his project.
"But i am on a journey right now" cryed the poor developer.
"That we don't care" said the Super Awesome Company.
So, the poor developer asked Sir BitBucket to pass him his files, so that the poor developer could make the changes from his friends home. While working, he noticed how powerful Mighty CodeKit was, since even there his file changed every now and then. When he finished, he gave his files back to Sir BitBucket, then, after having spent the rest of the journey with his friends, he came back home.

Back in his home, the poor developer asked Sir BitBucket his files, cause he had to make other works on it, but Sir BitBucket said him "I can't give you your file, cause your codekit-config has changed (again)."
"I know, but what can i do about that?" asked the poor developer.
"If that is you who made the changes, than you have to tell me which one is good and which one is bad. Otherwise, you have to get rid of the changes, so that i can give your files back to you" answered Sir BitBucket.
"How poor i am" said the poor developer.
"Why do you say that?" asked Sir BitBucket.
"Cause i need to travel a lot, and every time i must remember to get rid of changes made by Mighty CodeKit, since he will not do anything about that" answered the poor developer.
"Have you asked him if he can solve the problem? Being so Mighty, it should not be suche a problem for him ..."
"I did, but he blame you to solve that" said the poor developer.
"Me?" asked Sir BitBucket, astonished.
"Yes, he said something about the way you keep the file"
"I cannot believe that ... it must be the response of one of his Apple slave, captured during one of his raid in the land of Cupertino" allegated Sir BitBucket
"That is possible, but i can't know" said the poor developer.
## 

moral of the history
This is no way a git issue, and git itself has no problem in handling merging of codekit-config.json changes when it change, so please do not answer that one can "solve" the problem by changing whe way git deal with the file.
Also, suggesting to disable auto-update of the file neither is a solution, cause a disable auto-update means i have to remember to manually save the file every time i change something in the project: not having to deal with mnemonic tasks is one of the reason i bought your app and use it on daily basis, so disabling that is not an option.

You said once that this behaviour (how CodeKit write the configuration files in different ways every time) depends on the new refresh code and that "this way refresh is much faster" (event if i do not understand how a list of option can be sorted differently every time, i can accept it as an explanation); from my perspective this is not acceptable: there's no way i can trade refresh speed (which is a task that almos always run in background) with all the time i loose in order to keep the file correctly in sync between my two dev machines.

Also from my perspective the solution to this (which i can see i'm not the only one having to deal with) is pretty simple (logically speaking): either you disable entirely the "speedy refresh thing" in order to have a consistent config file or at least you add an option (on a per project basis) to keep the config file sorted.

**Comment by bdkjones** [comment] 2013-01-13 09:08
TLDNR :) Closed as a duplicate of #482. See comments there.

**Closed as completed by bdkjones** 2013-01-13 09:08 UTC
