### ISSUE TITLE
Chrome Freezing

### ISSUE THREAD

**Issue by TuckerWhitehouse** [bdkjones/CodeKit-1-Old#197] opened 2012-02-14 19:03 UTC
When using CodeKit for a long period of time (say 4 hours straight or so, constantly making changes to html/css/and js files in a project, with auto-reloading in chrome, chrome begins to freeze, and become unable to load any web pages. When I try and click on CodeKit in the menu bar, I get the spinning pinwheel and am unable to open it (or force quit it form here, because it's running as a menu bar app and does not show up in the Cmd+Alt+Esc window).

Not sure if this is an issue with how CodeKit reloads the pages in Google Chrome and overloads it, but a full system restart is usually required to get both programs to close.

In case in matters I'm using Google Chrome Dev v19.0.1036.7, but its been happening in the chrome dev since CodeKit version 1.0 (5158).

**Comment by bdkjones** [comment] 2012-02-14 19:12
Hi Tucker,

Are you using some framework such as CodeIgnitor? Other folks have reported this issue, but the problem is not CodeKit. Here's how it works:

1) They make a change to some file in their website.
2) CodeKit sees the change, and reloads Chrome.
3) During reload, the change that the user made introduced an error that CodeIgnitor (or another framework) sees.
4) CodeIgnitor (or another framework) is set up to log this error message to a certain file, usually a PHP file somewhere in the website's project folder.
5) CodeKit sees that another PHP file changed (when CodeIgnitor) wrote the log entry to it
6) CodeKit reloads Chrome in response to the newly-changed PHP file.
7) Infinite loop.

This causes both CodeKit and Chrome to appear locked up. The solution is to make sure that the log file is ignored by CodeKit, either by adding it to the "skipped items" list in the preferences window or selecting it in the project and checking the box that says "Do not reload browsers on save"

Also, can you verify that this issue affects the shipping version of Chrome, rather than just the accelerated dev channel version?

**Comment by TuckerWhitehouse** [comment] 2012-02-14 19:20
I'm actually not using any frameworks. Straight HTML and CSS (LESS) basically.

I'm not sure about the shipping version of chrome, i'll try installing that and see if the issue persists.

Could it be possible that an excessive amount of reloads could be causing this issue, because i'm currently using Chocolat as my editor, and I believe it is saving every time I pause typing for a few seconds, causing excessive reloads in CodeKit and Chrome.

**Comment by bdkjones** [comment] 2012-02-14 19:27
The answer is: I don't know. 

Browser reloading is about to get a whole lot better in Beta 9, so see if this issue is resolved with the next release, which will be out in the next few days.

**Comment by TuckerWhitehouse** [comment] 2012-02-14 19:29
Haha sounds good :)

LiveJS right?

~Thanks

**Comment by bdkjones** [comment] 2012-02-18 05:26
Beta 9 is live. Can you try it and see if it resolves the issue?

**Comment by TuckerWhitehouse** [comment] 2012-02-18 05:42
Just downloaded, put it through a good test tomorrow.

I did notice that working with file:/// url's will no longer work with the "When possible, inject changes without a full reload" because it can't complete an XHR request with a local file.

**Comment by TuckerWhitehouse** [comment] 2012-02-24 17:33
All seems to be well with the new build for me. Saw others were having an issue with the latest build, but i'm guessing it's a different issue where mine has been resolved.

**Closed as completed** 2012-02-24 17:33 UTC
