### ISSUE TITLE
JS Import via comments

### ISSUE THREAD

**Issue by Gidgidonihah** [bdkjones/CodeKit-1-Old#51] opened 2011-09-20 20:20 UTC
At the bottom of my js file i have the following block just for information purposes:

<pre>/* CodeKit is used to import (concatenate) these files and minifies the resulting file.
 * If you modify this file WITHOUT using CodeKit the following files will not be imported and things WILL fail.
 * The resulting file should be located in ./min/members-min.js
 */

// @import 'include/jqueryCookie.js'
// @import 'include/hasEventListener.js'
// @import 'include/gritter.js'
// @import 'include/modernizrAdditions.js'
// @import 'include/jqueryTemplates.js'
// @import 'include/jqueryNestedSortable.js'
// @import 'include/ajaxUpload.js'
// @import 'include/Date.getTextMonth.js'
</pre>

I'd love for CodeKit to see those import comments and use that information, rather than what to import being stored in some data file in application support.

**Comment by bdkjones** [comment] 2011-09-20 22:08
Yea... I discussed this with several JavaScript gurus. There are many issues that come up with @import statements in JavaScript, which is why the language doesn't have one.

Even the use of require() is pretty controversial. It's lots of little things like variable namespace collisions, etc.

Plus, CodeKit only supports prepending or appending imports. It's a terrible idea to allow devs to just stick any JS code anywhere with an @import. People would abuse that.

I envisioned the import functionality as a way to combine complete scripts into a single file, not drop code segments in anywhere you please, like say Less or Sass imports.

However, I have not ruled out something like:

@codekit-import-prepend "someScript.js"

Or 

@codekit-import-append "aScript.js"

The issue is that the app is designed to use only one of append or prepend per base file. That is, all imported files are EITHER prepended or appended. This keeps it simple.

**Comment by Gidgidonihah** [comment] 2011-09-20 22:13
I have no problem with it being a codekit proprietary thing. I'm not looking for importing in the middle of the file or anything else. Basically I love how codekit does things right now. Lets me keep the plugins and everything in separate in the codebase, but together for the end user.

The only thing I want is for that information to be stored IN THE FILE, rather than outside of the codebase. As it is now, there would be no indication in the codebase that those files are appended in the resulting minified file.

@codekit-import-prepend "someScript.js" and @codekit-import-append "aScript.js" sound great to me.

**Comment by bdkjones** [comment] 2011-10-03 20:52
I am closing this issue.

After a HOLY METRIC TON of work and re-coding, CodeKit is now architected to deal with @imports in a much more powerful way.

Bottom line:

I'm bringing two keywords to javascript/coffeescript files:

// @codekit-prepend "jQuery.js";
// @codekit-append "../../someOtherScript.js";

**Closed as completed by bdkjones** 2011-10-03 20:52 UTC

**Comment by AlejandroColinaPew** [comment] 2017-06-15 23:59
it would be wonderful if CK would help me build javascript,less,css,etc.files in any way I like, and then let me feed that it into babel, less,etc unhindered. if it fails , well it fails just like it does now when I code poorly.

**Comment by AlejandroColinaPew** [comment] 2017-06-16 00:06
Just realized this is about CodeKit 1. But Im pretty sure CodeKit 3 is the same
