### ISSUE TITLE
Import Linking: handle "./" syntax

### ISSUE THREAD

**Issue by badabam** [bdkjones/CodeKit-1-Old#367] opened 2012-07-11 09:24 UTC
I have one main less file that imports all the others. All the other files are set to "Do not compile directly" - they would not compile anyway, they are just parts of the one main less file.

When I change one of these files, I want the main less file to compile. But it seems that it does not detect the change.

**Comment by bdkjones** [comment] 2012-07-11 15:16
Just tested and this is working fine over here. Please email me an example project that shows the issue.

**Comment by badabam** [comment] 2012-07-11 17:10
Thank you!
I added an example. You can see my CodeKit settings in the settings.png.

When I change some less file other than styles.less, it will not compile.

What can I do? I guess it is the folder structure -> but I am not allowed
to change it.

Thanks again!
- Jerry

2012/7/11 bdkjones <
reply@reply.github.com

> Just tested and this is working fine over here. Please email me an example
> project that shows the issue.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bdkjones/CodeKit/issues/367#issuecomment-6909537

## 

Jeremias Dombrowsky

0151 23421980
jerry@badabam.de

Lessers Passage 10
22767 Hamburg

**Comment by bdkjones** [comment] 2012-07-11 17:37
... not seeing any attachments or examples.

**Comment by badabam** [comment] 2012-07-11 20:20
That is weird, I added a zip (just checked my sent mailbox).

You can download it here: http://ge.tt/4SsbpMK/v/0?c

Greetings
Jerry

## 

Jeremias Dombrowsky

0151 23421980
jerry@badabam.de

Lessers Passage 10
22767 Hamburg

Am 11.07.2012 um 19:37 schrieb bdkjones:

**Comment by bdkjones** [comment] 2012-07-12 05:41
Got it. The issue is simple: do not use the period to indicate the current directory in your import statements. It's superfluous. Change the import statements in "styles.less" to look like this:

```
@import "some/folder/somewhere/file.less
```

rather than

```
@import "./some/folder/somewhere/file.less
```

That said, I will make a note to adjust the import linking algorithm to properly deal with the ./ syntax.

**Comment by bdkjones** [comment] 2012-07-12 05:54
Issue fixed in build 6509. Will be in the next release.

**Closed as completed by bdkjones** 2012-07-12 05:54 UTC
