### ISSUE TITLE
Watch for file name changes

### ISSUE THREAD

**Issue by pyronaur** [bdkjones/CodeKit-1-Old#225] opened 2012-02-21 20:07 UTC
1. Make file "tasty.coffee"
2. (right click in CK): "Choose Output Folder"
3. Set output folder to "x/foo"
4. Rename file to "drink.coffee"
5. Set output folder to "x/bar"
6. Compile drink.coffee

File compiled successfully: "x/bar/tasty.js"

Steps 5 and 6 not necessary, it is already a bug since Step 4 :).

**Comment by bdkjones** [comment] 2012-02-22 19:09
In step 5 ---> are you setting the output path by right-clicking on "drink.coffee" and selecting a new folder, or are you changing the preferences for default output paths in the preferences window?

**Comment by pyronaur** [comment] 2012-02-22 20:30
By right clicking on "drink.coffee"
And as I said - The bug is already a bug at step 4.

**Comment by bdkjones** [comment] 2012-02-22 20:43
No, it's not a bug at step 4. 

This was actually a conscious decision on my part. When you rename a file, CodeKit does NOT automatically rename the output file as well. This is because you've likely got that output file in tags in various pages and if CodeKit automatically renamed it, those tags would not point to a valid file. Worse, the old file would still exist so you'd compile stuff and not understand why you weren't seeing changes.

So you'd email me and tell me my app was broken and I'd have to respond and say, "Well, did you update the tags in your page HEAD elements to point to the new output files?" and you'd go, "Oh." And much time would be wasted all around.

Point being: this is only a bug if step 5 isn't working, and, again, it works great over here. Can you send me a demo project that shows the issue?

**Comment by pyronaur** [comment] 2012-02-22 20:44
Will do a recheck of this right now.

**Comment by pyronaur** [comment] 2012-02-22 21:13
http://www.mediafire.com/?c22f5gfvtkn96k8

**Comment by bdkjones** [comment] 2012-02-22 21:17
Ahh, okay, the video cleared it up.

The output filename doesn't change when you set the output path manually after renaming the source (creator) file. Got it. It should definitely change after you manually select a new output path, it just shouldn't automatically change as soon as you rename the creator file.

Great catch.

**Comment by pyronaur** [comment] 2012-02-22 21:26
A shortcut button for that wouldn't hurt either :). 
I use CodeKit to develop not just for web. For example in CommonJS (Node.js, Appcelerator Titanium) I use `require "jsfile"` instead of `require "jsfile.js"`, and I don't even have to think much about .js files, except for debugging.
When I rename something, I expect it to be renamed in both places.I agree that in the web the opposite could be true, but as I said, I use codekit for more than just that. - so a little switch or a button to rename the file easily would be great!

p.s. Thank you for the perfect development tool.

**Comment by davidhund** [comment] 2012-02-25 21:44
I just got bit by this too. Is there any (tmp) workaround for this (maybe editing some pref-file) or should I remove/re-add the source file?

**Comment by pyronaur** [comment] 2012-02-26 01:23
Copy contents of the file you want to rename. Delete it. Save it as a new file name. Probably the most painless workaround at the moment.

**Comment by bdkjones** [comment] 2012-03-18 08:09
Issue resolved in 5910 by adding the ability to specify filenames when setting output paths.

**Closed as completed by bdkjones** 2012-03-18 08:09 UTC
