### ISSUE TITLE
After injecting compiled css transitions are everywhere

### ISSUE THREAD

**Issue by thelitek** [bdkjones/CodeKit-1-Old#359] opened 2012-06-21 08:12 UTC
Sometimes after saving and compiling compass project, new css gets injected in to Chrome (19.0.1084.56) but the class "livejs-loading" isn't removed resulting in transitions on everything - actually it's funny for the first few seconds, but no longer.

**Comment by nicooprat** [comment] 2012-06-29 07:12
Second this. Transitions should be applied only for live reloading, and removed after.

**Comment by edwardsdesign** [comment] 2012-07-20 15:27
I have an issue with this as well. I have to manually reload the browser to clear the livejs so I can test the project specific transitions I have put in place.

**Comment by nicooprat** [comment] 2012-09-25 07:35
OR, there could be an option to (des)activate CSS transitions while injecting ?

**Comment by bdkjones** [comment] 2012-09-25 20:23
If you inspect the CSS rule that CodeKit adds to the head element, it applies only to elements inside an element with a specific class. Once CodeKit is done refreshing, it removes that class name from the relevant elements, which should prevent the transition from applying.

Are you guys seeing the loading class remaining on elements after CodeKit is finished injecting new CSS?

**Comment by nicooprat** [comment] 2012-09-26 10:06
Yeah I saw that rule, and no, it does not remain.

I must say that, actually, this bug didn't happen to me since a moment... and as I already had some troubles with CSS transitions in Chrome, I'm wondering if it was not a bug in Webkit that has been fixed since.

**Comment by bdkjones** [comment] 2012-11-15 05:58
Fixed in 1.3.1

**Closed as completed by bdkjones** 2012-11-15 05:58 UTC
Labels: Greenlit TODO
